name: 'Updating Stars'
# This workflow runs at 00:30 everyday.
on:
  schedule:
    - 
      cron: '30 18 * * *'
jobs:
  build:
    name: 'stargazed update'
    runs-on: ubuntu-latest
    steps:
      - 
        name: 'Use GitHub Actions'
        uses: actions/checkout@v2
      - 
        name: 'Use Node.js 12.x'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - 
        name: 'Install Package'
        run: 'npm install --global stargazed'
      - 
        name: 'Update Repo'
        env:
          GITHUB_TOKEN: '${{ secrets.GH_TOKEN }}'
        run: 'stargazed --username  "abhisheknaiidu" --token ${GITHUB_TOKEN} --repository "nads" --message "stargazed update by GitHub Actions Workflow" -s -w'
